# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('reciever', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('is_attachment', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=254)),
            ],
        ),
    ]
