# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170128_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='isFile',
            field=models.BooleanField(default=True),
        ),
    ]
