# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_policy_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='customer_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
