# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_policy_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='term',
        ),
    ]
